version: '3.1'
services:
  test:
    image: postgres:alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgres
    environment:
      - POSTGRES_DATABASE=vin
      - POSTGRES_USER=vin
      - POSTGRES_PASSWORD=12345TyHs231